sudo: required
language: node_js
node_js:
  - "7"

addons:
apt:
  sources:
    - google-chrome
    packages:
      - google-chrome-stable
      - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g  --silent @angular/cli

script:
  - ng test --single-run
  - if [ "$TRAVIS_BRANCH" == "master" ]; then ng build --prod; fi
  - if [ "$TRAVIS_BRANCH" != "master" ]; then ng build; fi

deploy:
  - provider: firebase
    token:
      secure: $FIREBASE_TOKEN
    project: prod
    skip_cleanup: true
    on:
      branch: master
  - provider: firebase
    token:
      secure: $FIREBASE_TOKEN
    project: dev
    skip_cleanup: true
    on:
      branch: develop
